apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-istio
  namespace: backend-services
  labels:
    app: demo-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-istio
  template:
    metadata:
      labels:
        app: demo-istio
    spec:
      containers:
        - name: demo-istio
          image: adama93/demo-istio:v1
          imagePullPolicy: Always #we want to pull the image locally
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            - name: DB_NAME  # Setting Database name from configMap
              value: db_product
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root

---
apiVersion: v1
kind: Service
metadata:
  name: demo-istio
  namespace: backend-services
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: demo-istio
  type: ClusterIP